name: Tests

on:
  workflow_call:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
        - main

permissions:
  contents: read

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  linux:
    needs: pre-commit
    uses: ./.github/workflows/tests-linux.yml

  macos:
    needs: pre-commit
    uses: ./.github/workflows/tests-macos.yml

  windows:
    needs: pre-commit
    uses: ./.github/workflows/tests-windows.yml
