name: Tests

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update rust toolchain
        run: rustup update && cargo install maturin
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - uses: pre-commit/action@v3.0.0

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Update
      run: rustup update
    - name: Install maturin
      run: cargo install maturin
    - name: Build
      run: maturin develop --release
    - name: Rust tests
      run: cargo test --release
    - name: Python tests
      run: pytest
